### ISSUE TITLE
Config to exclude directories from rails_best_practices

### ISSUE THREAD

**Issue by noahsw** [metricfu/metric_fu#263]
I'm trying to exclude my `/config/chef` folders from rails_best_practices but it doesn't seem like the plumbing is in place to do so.

On https://github.com/metricfu/metric_fu/blob/master/lib/metric_fu/metrics/rails_best_practices/generator.rb#L10, you can see we hardcode in `"silent" => true`. Based on https://github.com/railsbp/rails_best_practices/blob/master/lib/rails_best_practices/analyzer.rb#L32, we could also pass in `"excude" => folder`.

**Comment by bf4** [comment]
Looks good to me.  Would you be up for a PR? Want to pair on it?

**Comment by noahsw** [comment]
Sure, I can give it a crack. How do you want to pair? 

I started at https://github.com/metricfu/metric_fu/compare/master...noahsw:rails_best_practices_options?expand=1

**Comment by bf4** [comment]
Looks about right on visual inspection. I've been neglecting for a while all the awesome I've wanted to put into metric_fu. 

This week after 8:30pm America/Central I might have time, otherwise perhaps Sunday.  I'm reachable http://benjaminfleischer.com/pair (I hate putting email addresses on public sites.. old habit I guess)
